import { images } from './images'

// Recorded Classes. Titles, lengths and prices are PLACEHOLDERS for Kirti to replace.
// Phase 1: each class links to a Razorpay or Stripe checkout. Phase 2: a video library.

export const classes = {
  intro: {
    label: 'Recorded Classes',
    headline: [{ text: 'Practise at home,' }, { text: 'in your own time.', italic: true }],
    lede: 'Guided classes you can return to as often as you like. Each one is complete in itself: a mat, a quiet floor and the length of the recording are all you need.',
  },

  filters: [
    { id: 'all', label: 'All classes' },
    { id: 'somatics', label: 'Somatics' },
    { id: 'tai-chi', label: 'Tai Chi' },
    { id: 'creative-movement', label: 'Creative Movement' },
  ],

  placeholder: false,

  items: [
    {
      id: 'neck-shoulder-freedom',
      practice: 'somatics',
      practiceName: 'Clinical Somatics',
      title: 'Neck and Shoulder Freedom',
      subtitle: 'Gentle pandiculation to release chronic trapezius tightness, desk posture strain, and habituated shoulder elevation.',
      focus: 'Slow releases for the muscles that lift and round the shoulders.',
      duration: '45 min',
      level: 'All levels',
      price: '₹600',
      originalPrice: '₹1,200',
      rating: 4.9,
      ratingCount: 148,
      studentsCount: 390,
      lastUpdated: 'October 2026',
      image: images.reach,
      overview: [
        'When you sit at a desk, work under deadline pressure, or carry emotional strain, your nervous system triggers the startle reflex: tightening the trapezius, elevating the shoulders, and shortening the front of the neck. Over weeks and months, the brain forgets how to fully relax these muscles, a state Thomas Hanna identified as Sensory Motor Amnesia.',
        'Stretching tight neck muscles often triggers the protective stretch reflex, causing the tissue to grip back harder. This guided somatic class uses pandiculation: conscious contraction followed by decelerated, mindful lengthening. You learn to remind your motor cortex how to let the shoulder blades drop down into gravity without force.',
      ],
      whatYouWillLearn: [
        'Identify involuntary tension held in the trapezius, levator scapulae, and pectorals',
        'Master the slow shoulder clock pandiculation for neck and collarbone ease',
        'Release chronic suboccipital tension at the base of the skull',
        'Restore free rotation of the cervical spine without joint pinching',
        'Establish an effortless 5-minute daily reset you can practice at your desk',
      ],
      requirements: [
        'A quiet space on a floor mat, rug, or firm bed',
        'Comfortable clothing that allows your ribs and shoulders to move freely',
        'No prior somatic movement experience needed',
      ],
      includes: [
        '45 minutes on-demand high-definition video lesson',
        'Downloadable audio-only pandiculation companion (MP3)',
        'Printable illustrated movement sequence guide (PDF)',
        'Lifetime streaming access on laptop, tablet, and mobile',
      ],
      curriculum: [
        {
          id: 'lesson-1',
          title: '01. Arriving & Neuromuscular Assessment',
          duration: '6:30',
          previewable: true,
          summary: 'Sensing where the shoulder blades rest against gravity before initiating movement.',
        },
        {
          id: 'lesson-2',
          title: '02. The Shoulder Clock Pandiculation',
          duration: '18:45',
          previewable: false,
          summary: 'Systematic gentle contraction and decelerated release across all four quadrants.',
        },
        {
          id: 'lesson-3',
          title: '03. Freeing the Cervical Spine & Suboccipitals',
          duration: '12:15',
          previewable: false,
          summary: 'Coordinating head rolling with shoulder release to unlock neck mobility.',
        },
        {
          id: 'lesson-4',
          title: '04. Standing Integration & Postural Ease',
          duration: '7:30',
          previewable: false,
          summary: 'Standing up, sensing weight transfer, and checking the new baseline of lightness.',
        },
      ],
    },
    {
      id: 'lower-back-release',
      practice: 'somatics',
      practiceName: 'Clinical Somatics',
      title: 'Releasing the Lower Back',
      subtitle: 'Somatic pandiculation for the arch and flatten reflex, releasing habituated lumbar contraction and pelvic tilt.',
      focus: 'Pandiculation for the long muscles of the spine and the waist.',
      duration: '40 min',
      level: 'All levels',
      price: '₹600',
      originalPrice: '₹1,200',
      rating: 4.9,
      ratingCount: 162,
      studentsCount: 420,
      lastUpdated: 'October 2026',
      image: images.lowerBackRelease,
      overview: [
        'Chronic lower back stiffness is rarely a spine problem: it is an action pattern. The Landau reflex contracts the extensor muscles along the lumbar vertebrae whenever we brace for productivity, stand for hours, or hurry through the day.',
        'In this class, you practice the foundational somatic movements of the pelvis and lumbar spine. Through slow, pleasurable pandiculations, your brain regains voluntary motor control over the erector spinae and quadratus lumborum, restoring natural curve and pain-free movement.',
      ],
      whatYouWillLearn: [
        'Release involuntary spasm in the lower back and waist muscles',
        'Perform the classic Somatic Arch and Flatten with biological ease',
        'Repattern pelvic tilting and eliminate SI joint strain',
        'Learn the Diagonal Back Lift to rebalance asymmetrical tightness',
        'Wake up in the morning without that familiar lumbar stiffness',
      ],
      requirements: [
        'A comfortable floor mat or soft carpet',
        'A small towel or thin pillow for under the head if needed',
        'Willingness to move at twenty percent effort for maximum neural feedback',
      ],
      includes: [
        '40 minutes guided video sequence with clear spoken guidance',
        'Audio pandiculation track for screen-free bed or floor practice',
        'Illustrated printable guide for the 4 core lumbar movements',
        'Lifetime unlimited access across all your devices',
      ],
      curriculum: [
        {
          id: 'lesson-1',
          title: '01. The Somatic Baseline Assessment',
          duration: '5:15',
          previewable: true,
          summary: 'Noticing the space between the lower back and the floor.',
        },
        {
          id: 'lesson-2',
          title: '02. Arch and Flatten Neuromuscular Reset',
          duration: '16:20',
          previewable: false,
          summary: 'The primary pandiculation movement for the lumbar extensors and abdominals.',
        },
        {
          id: 'lesson-3',
          title: '03. The Diagonal Waist and Pelvic Reach',
          duration: '11:45',
          previewable: false,
          summary: 'Addressing side-to-side asymmetries and hips held tight from walking or sitting.',
        },
        {
          id: 'lesson-4',
          title: '04. Integration & Gentle Standing Walk',
          duration: '6:40',
          previewable: false,
          summary: 'Bringing the restored mobility of the lumbar curve into your everyday stride.',
        },
      ],
    },
    {
      id: 'standing-like-a-tree',
      practice: 'tai-chi',
      practiceName: 'Tai Chi',
      title: 'Standing Like a Tree',
      subtitle: 'A foundational Zhan Zhuang moving meditation for rooted leg strength, settled breath, and effortless equilibrium.',
      focus: 'A standing practice for rooting, balance and a settled breath.',
      duration: '25 min',
      level: 'Beginners',
      price: '₹400',
      originalPrice: '₹800',
      rating: 4.8,
      ratingCount: 110,
      studentsCount: 295,
      lastUpdated: 'September 2026',
      image: images.taiChiStanding,
      overview: [
        'Zhan Zhuang (standing meditation) is the cornerstone of internal martial arts. By standing in alignment without rigid tension, the skeletal frame carries the body weight and muscles are allowed to release into gravity.',
        'This 25-minute practice teaches you how to sink your weight into the feet, unlock the hips (the Kua), and allow the diaphragm to drop naturally. You discover stillness that does not feel stiff, but vibrantly alive.',
      ],
      whatYouWillLearn: [
        'Root your body weight into the three points of the feet',
        'Open the lower back and suspend the crown as if by a silk thread',
        'Calm mental chatter through continuous somatic body scanning',
        'Develop steady legs without joint strain or knee pressure',
      ],
      requirements: [
        'Flat footwear or bare feet on a level surface',
        'A few feet of clear space around you',
      ],
      includes: [
        '25 minutes high-definition standing instruction',
        'Audio guide track for outdoor park or balcony practice',
        'Posture alignment breakdown checklist',
      ],
      curriculum: [
        {
          id: 'lesson-1',
          title: '01. Alignment: The Three External Harmonies',
          duration: '6:10',
          previewable: true,
          summary: 'Shoulders over hips, knees over toes, crown suspended from above.',
        },
        {
          id: 'lesson-2',
          title: '02. Embracing the Tree (Wuji to Zhan Zhuang)',
          duration: '14:20',
          previewable: false,
          summary: 'Holding the round circle posture while releasing tension layer by layer.',
        },
        {
          id: 'lesson-3',
          title: '03. Gathering Chi and Quiet Closing',
          duration: '4:30',
          previewable: false,
          summary: 'Storing energy in the lower dantian and settling back into daily life.',
        },
      ],
    },
    {
      id: 'spine-stories',
      practice: 'creative-movement',
      practiceName: 'Creative Movement',
      title: 'Spine Stories',
      subtitle: 'Guided somatic dance inquiry that unlocks expressive articulation, spinal rhythm, and emotional lightness.',
      focus: 'Guided improvisation that begins and ends with the spine.',
      duration: '35 min',
      level: 'All levels',
      price: '₹500',
      originalPrice: '₹1,000',
      rating: 5.0,
      ratingCount: 88,
      studentsCount: 210,
      lastUpdated: 'October 2026',
      image: images.fluidMovement,
      overview: [
        'Your spine is a cascade of twenty-four vertebrae designed for waves, spirals, and expressive storytelling. Modern life often flattens this movement into rigid columns of posture.',
        'Spine Stories is an invitation to move without mirrors or choreography. Guided prompts gently invite each segment of your spine into curious, playful motion, shaking loose emotional holding patterns.',
      ],
      whatYouWillLearn: [
        'Explore spinal articulation through wave, spiral, and ripple dynamics',
        'Move from inner sensation rather than external aesthetics',
        'Release inhibitions and performance anxiety around dance',
        'Restore spontaneous fluidity to your ribs, neck, and pelvis',
      ],
      requirements: [
        'Space to take a few steps in all directions',
        'Comfortable clothes you feel totally free in',
      ],
      includes: [
        '35 minutes experiential movement video',
        'Curated acoustic musical soundscape for practice',
        'Journaling reflection prompts for post-movement contemplation',
      ],
      curriculum: [
        {
          id: 'lesson-1',
          title: '01. Grounding and Awakening the Spine',
          duration: '7:40',
          previewable: true,
          summary: 'Micro-movements on the floor tracing the natural contours of the vertebrae.',
        },
        {
          id: 'lesson-2',
          title: '02. Spiral Dynamics & The Living Column',
          duration: '18:10',
          previewable: false,
          summary: 'Guiding the spine from floor to standing through continuous fluid spirals.',
        },
        {
          id: 'lesson-3',
          title: '03. Free Expression & Still Landing',
          duration: '9:10',
          previewable: false,
          summary: 'Unstructured movement integration followed by quiet resting contemplation.',
        },
      ],
    },
    {
      id: 'the-easy-breath',
      practice: 'somatics',
      practiceName: 'Clinical Somatics',
      title: 'The Easy Breath',
      subtitle: 'Neuromuscular releases for the ribs, diaphragm, and abdominal wall to restore deep, unforced respiration.',
      focus: 'Softening the belly and ribs so the breath can deepen without effort.',
      duration: '30 min',
      level: 'All levels',
      price: '₹500',
      originalPrice: '₹1,000',
      rating: 4.9,
      ratingCount: 135,
      studentsCount: 340,
      lastUpdated: 'September 2026',
      image: images.sideBend,
      overview: [
        'Deep breathing cannot happen in a tight ribcage. When the intercostal muscles and diaphragm are held in chronic tension from anxiety, forcing deep breaths only causes fatigue.',
        'This somatic sequence guides you through gentle pandiculations for the chest, side body, and abdominal wall, giving the diaphragm space to expand freely on its own.',
      ],
      whatYouWillLearn: [
        'Release chronic tightness in the intercostal muscles between the ribs',
        'Allow the diaphragm to descend without forceful belly pushing',
        'Calm the sympathetic nervous system within minutes',
        'Experience breathing as a full-body three-dimensional expansion',
      ],
      requirements: [
        'A warm, quiet spot to lie down',
        'No constricting belts or tight waistbands',
      ],
      includes: [
        '30 minutes high-definition guided somatic breath lesson',
        '10-minute bedtime relaxation audio track',
        'Breath awareness diagram with key anatomical landmarks',
      ],
      curriculum: [
        {
          id: 'lesson-1',
          title: '01. Sensing the Three-Dimensional Breath',
          duration: '6:15',
          previewable: true,
          summary: 'Observing the natural breath rhythm without attempting to change it.',
        },
        {
          id: 'lesson-2',
          title: '02. Releasing the Ribs and Side Waist',
          duration: '15:30',
          previewable: false,
          summary: 'Gentle pandiculations that open the lateral ribs and intercostal spacing.',
        },
        {
          id: 'lesson-3',
          title: '03. The Uninhibited Diaphragm',
          duration: '8:15',
          previewable: false,
          summary: 'Releasing the front abdominal wall for effortless, calming breath depth.',
        },
      ],
    },
    {
      id: 'grounding-flow',
      practice: 'tai-chi',
      practiceName: 'Tai Chi',
      title: 'Grounding Flow: A First Form',
      subtitle: 'Eight linked traditional postures taught with precise footwork, circular transitions, and internal relaxation.',
      focus: 'Eight linked postures, taught slowly, to carry into daily practice.',
      duration: '50 min',
      level: 'Beginners',
      price: '₹700',
      originalPrice: '₹1,400',
      rating: 4.9,
      ratingCount: 95,
      studentsCount: 260,
      lastUpdated: 'October 2026',
      image: images.taiChiWall,
      overview: [
        'Learn a continuous sequence of eight essential Tai Chi postures designed for daily morning practice. Every movement is broken down step by step with close attention to foot placement, waist turning, and breath.',
        'This class bridges the gap between mechanical exercise and moving meditation, leaving you grounded, centered, and physically coordinated.',
      ],
      whatYouWillLearn: [
        'Learn the choreography and internal intention of eight classic movements',
        'Master smooth weight shifting without wobbling or knee torque',
        'Coordinate arm gestures with rotation from the dantian',
        'Establish a standalone 10-minute daily morning movement ritual',
      ],
      requirements: [
        'Space to take three paces in either direction',
        'Comfortable footwear with flat, flexible soles or bare feet',
      ],
      includes: [
        '50 minutes in-depth posture-by-posture video tutorial',
        'Continuous practice follow-along video with minimal talking',
        'Postural reference chart with Chinese and English names',
      ],
      curriculum: [
        {
          id: 'lesson-1',
          title: '01. Opening the Form & Stepping Dynamics',
          duration: '10:20',
          previewable: true,
          summary: 'Sinking weight and stepping without committing until rooted.',
        },
        {
          id: 'lesson-2',
          title: '02. Postures 1 to 4: Ward Off, Roll Back, Press, Push',
          duration: '21:10',
          previewable: false,
          summary: 'The fundamental grasping sparrow’s tail sequence explained in detail.',
        },
        {
          id: 'lesson-3',
          title: '03. Postures 5 to 8: Single Whip to Closing',
          duration: '18:30',
          previewable: false,
          summary: 'Expanding out into the perimeter and gathering balance back to center.',
        },
      ],
    },
  ],

  courses: {
    heading: 'Short courses are on the way',
    body: 'Sequenced courses of four to six classes are being recorded. Field Notes subscribers will hear first.',
    secondary: { to: '/articles#field-notes', label: 'Subscribe to Field Notes' },
  },
}
